# Generated by Django 4.0.4 on 2022-06-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogi', '0002_post_julkaisu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='kategoria',
            field=models.CharField(default='ei kategoriaa', max_length=255),
        ),
    ]
