# Generated by Django 4.0.4 on 2022-06-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogi', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kuvan_malli',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
