# Generated by Django 4.0.4 on 2022-06-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogi', '0008_profiili'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiili',
            name='profiili_kuva',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiili/'),
        ),
        migrations.AddField(
            model_name='profiili',
            name='some_fb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profiili',
            name='some_insta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
